/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CauThuConTroller;
import controller.ClLBController;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.CLB;
import model.CauThu;

/**
 *
 * @author Dell
 */
public class EditCauThuFrm extends javax.swing.JDialog {

    /**
     * Creates new form EditCauThuFrm
     */
    
    int macauthu = 0;
    List<CLB> ClbList;
    HomeFrm homeFrm;
    
    public EditCauThuFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cập nhật cầu thủ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbTenDoi = new javax.swing.JLabel();
        jlbTenCauThu = new javax.swing.JLabel();
        jlbNgaySinh = new javax.swing.JLabel();
        jlbSoAo = new javax.swing.JLabel();
        jlbViTri = new javax.swing.JLabel();
        cbTenDoi = new javax.swing.JComboBox<>();
        jtfTenCauThu = new javax.swing.JTextField();
        jtfNgaySinh = new javax.swing.JTextField();
        jtfViTri = new javax.swing.JTextField();
        jtfSoao = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jlbImage = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfImage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN CẦU THỦ");

        jlbTenDoi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbTenDoi.setText("Tên đội:");

        jlbTenCauThu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbTenCauThu.setText("Tên cầu thủ:");

        jlbNgaySinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbNgaySinh.setText("Date (DD/MM/YYYY):");

        jlbSoAo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbSoAo.setText("Số áo:");

        jlbViTri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbViTri.setText("Vị trí:");

        cbTenDoi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfTenCauThu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfNgaySinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfViTri.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfViTriActionPerformed(evt);
            }
        });

        jtfSoao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfSoao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSoaoActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jlbImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Hình ảnh"));

        btnImage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImage.setText("SELECT IMAGE");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Link ảnh:");

        jtfImage.setEditable(false);
        jtfImage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnSave)
                .addGap(93, 93, 93)
                .addComponent(btnCancel)
                .addGap(53, 53, 53)
                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbTenCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTenDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbSoAo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbViTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTenCauThu)
                            .addComponent(jtfNgaySinh)
                            .addComponent(jtfViTri)
                            .addComponent(jtfSoao)
                            .addComponent(cbTenDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfImage, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTenDoi)
                            .addComponent(jlbTenDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbTenCauThu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfTenCauThu)
                                .addGap(5, 5, 5)))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSoAo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSoao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfImage, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfViTriActionPerformed

    private void jtfSoaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSoaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSoaoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ClbList = ClLBController.findAll();
        boolean isOK = true;
        int soao = 0, madoi = 0;
        Date ngaysinh = null;
        String tendoi = null, tencauthu = null, vitri = null, linkanh = null;

        if (cbTenDoi.getSelectedIndex() >= 0) {
            tendoi = cbTenDoi.getSelectedItem().toString();
            for(CLB clb : ClbList) {
                if(clb.getTendoi().equals(tendoi)) {
                    madoi = clb.getMadoi();
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn chưa chọn CLB");
            isOK = false;
        }
        if (jtfTenCauThu.getText().length() > 0 && jtfTenCauThu.getText() != null) {
            tencauthu = jtfTenCauThu.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn chưa nhập tên cầu thủ");
            isOK = false;
        }

        if (jtfNgaySinh.getText().length() > 0 && jtfNgaySinh.getText() != null) {
            try {
                ngaysinh = new SimpleDateFormat("dd/MM/yyyy").parse(jtfNgaySinh.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane,
                    "Bạn nhập sai định dạng, ngày sinh phải có định dạng dd/MM/yyyy");
                isOK = false;
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn chưa nhập ngày sinh");
            isOK = false;
        }

        if (jtfSoao.getText().length() > 0 && jtfSoao.getText() != null) {
            try {
                soao = Integer.parseInt(jtfSoao.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(rootPane,
                    "Số áo phải là số không thể chứa kí tự khác");
                isOK = false;
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn chưa nhập số áo");
            isOK = false;
        }
        
        if (jtfViTri.getText().length() > 0 && jtfViTri.getText() != null) {
            vitri = jtfViTri.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn chưa nhập vị trí");
            isOK = false;
        }
        
         if (jtfImage.getText().length() > 0 && jtfImage.getText() != null) {
            linkanh = jtfImage.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn chưa chọn ảnh cho cầu thủ");
            isOK = false;
        }

        if (isOK) {
            CauThu cauThu = new CauThu(madoi, macauthu, soao, ngaysinh, tencauthu, vitri, linkanh);
            JOptionPane.showMessageDialog(rootPane,
                    "Bạn đã cập nhật thành công cầu thủ");
            CauThuConTroller.update(cauThu);

            this.dispose();
        }
//        homeFrm = new HomeFrm();
//        homeFrm.ShowCauThu();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("C:\\Users\\Dell\\Documents\\NetBeansProjects\\football_league_management_1\\src\\image\\player");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY); // chỉ hiện thị file
        int returnValue = fileChooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            // lấy đường dẫn file
            String pathFile = file.getAbsolutePath();
            System.out.println(pathFile);
            BufferedImage b;
            try {
                b = ImageIO.read(file);
                jlbImage.setIcon(new ImageIcon(b.getScaledInstance(200, 200, Image.SCALE_SMOOTH)));
                jtfImage.setText(pathFile);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCauThuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCauThuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCauThuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCauThuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditCauThuFrm dialog = new EditCauThuFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbTenDoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JLabel jlbNgaySinh;
    private javax.swing.JLabel jlbSoAo;
    private javax.swing.JLabel jlbTenCauThu;
    private javax.swing.JLabel jlbTenDoi;
    private javax.swing.JLabel jlbViTri;
    private javax.swing.JTextField jtfImage;
    private javax.swing.JTextField jtfNgaySinh;
    private javax.swing.JTextField jtfSoao;
    private javax.swing.JTextField jtfTenCauThu;
    private javax.swing.JTextField jtfViTri;
    // End of variables declaration//GEN-END:variables

    void editCauThuData(CauThu cauThu) {
        showConboData();
        macauthu = cauThu.getMacauthu();
        cbTenDoi.setSelectedItem(cauThu.getTendoi());
        jtfTenCauThu.setText(cauThu.getTencauthu());
        jtfNgaySinh.setText(new SimpleDateFormat("dd/MM/yyyy").format(cauThu.getNgaysinh()));
        jtfSoao.setText(String.valueOf(cauThu.getSoao()));
        jtfViTri.setText(cauThu.getVitri());
        jtfImage.setText(cauThu.getLinkImage());
        
        File file = new File(cauThu.getLinkImage());
        // lấy đường dẫn file
        String pathFile = file.getAbsolutePath();
        BufferedImage b;
        try {
            b = ImageIO.read(file);
            jlbImage.setIcon(new ImageIcon(b.getScaledInstance(200, 200, Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    
    public void showConboData() {
        ClbList = ClLBController.findAll();
        cbTenDoi.removeAllItems();
        ClbList.forEach(clb -> {
            cbTenDoi.addItem(clb.getTendoi());
        });
    }
}

